#!/usr/local/bin/python3
import click
import datetime as dt
import json
import requests
import printer
import bcrypt
import dateutil.parser
import os
import sys

baseurl = "https://c448e6d2-b8c6-460c-9f06-b405cfa8cb01-ide.cs50.xyz:8080/api"

token = None

@click.group()
def main():
    pass

@main.command()
def today():
    today_start = dt.datetime.combine(dt.datetime.today(), dt.time(0)).strftime('%s')
    today_end = dt.datetime.combine((dt.datetime.today() + dt.timedelta(days=1)), dt.time(0)).strftime('%s')
    url = baseurl + "/events" + "?start=" + today_start + "&end=" + today_end
    events_today = requests.get(url, headers={'token': token})
    printer.pretty(events_today.text)

@main.command()
@click.option("--username", prompt="username")
@click.option("--password", prompt="password", hide_input=True)
def login(username, password):
    url = baseurl + "/login"
    credentials = {}
    credentials["username"] = username
    credentials["hash"] = (bcrypt.hashpw(password.encode(), bcrypt.gensalt(5))).decode()
    credentials["password"] = password
    pending = requests.post(url, json=json.loads(json.dumps(credentials)))
    if pending.status_code == 200:
        token_file = open(".token.json", "w")
        token_file.write(json.loads(pending.text))
        token_file.close()
        click.echo(click.style('successfully logged in.', fg='green'))
        click.echo(click.style('do not share your token stored in .token.json', fg='red', bold=True))
    else:
        click.echo(click.style('login failed. please try again,', fg='yellow', bold=True))

@main.command()
@click.argument("event_name", nargs=-1)
@click.option("--day", "-d", default=dt.date.today().strftime("%d/%m/%Y"), show_default=False, prompt="date", help="Date of the event")
@click.option("--start", "-t", default=dt.time(0).strftime("%-I:%M%p"), prompt="start time", help="Start time of the event", show_default=False)
@click.option("--duration", "-l", default='60', prompt="duration (minutes)", help="Duration of the event", show_default=False)
@click.option("--info", "-i", default='', prompt="information (optional)", help="Event Location", show_default=False)
def event(event_name, day, start, duration, info):
    url = baseurl + "/events"
    event_d = {"name": " ".join(event_name)}
    try:
        date = dateutil.parser.parse(day, dayfirst=True)
    except ValueError:
        click.echo(click.style('please enter a valid date', fg='red'))
    try:
        time = dateutil.parser.parse(start, dayfirst=True)
    except ValueError:
        click.echo(click.style('please enter a valid start time', fg='red'))
    start = dt.datetime.combine(date.date(), time.time())
    try:
        end = start + dt.timedelta(minutes=int(duration))
    except ValueError:
        click.echo(click.style('please enter an integer number of minutes', fg='red'))
    event_d['start'] = start.strftime("%s")
    event_d['end'] = end.strftime("%s")
    event_d['info'] = info
    pending = requests.post(url, json=json.loads(json.dumps(event_d)), headers={'token': token})
    if pending.status_code == 200:
        click.echo(f"-> event {json.loads(pending.text)['eventhex']} created")
    else:
        click.echo("failed")

@main.command()
@click.argument("reminder_name", nargs=-1)
@click.option("--day", "-d", default=dt.date.today().strftime("%-d/%-m/%Y"), prompt="Day", help="Date of the reminder")
@click.option("--time", "-t", default=dt.time(0).strftime("%-I:%M%P"), prompt="Time", help="Time of the reminder")
def remind(reminder_name, day, time):
    remind_d = {}
    remind_d["name"] = " ".join(reminder_name)
    remind_d["day"] = day
    remind_d["time"] = time
    json.loads(json.dumps(remind_d))
    click.echo(f"Reminder created {remind_d['name']} on {remind_d['day']} at {remind_d['time']}")

if __name__ == "__main__":
    try:
        token_file = open(".token.json", "r")
        token = token_file.read()
        token_file.close()
    finally:
        main()